# Workflow for deploying Storybook to GitHub Pages
name: Deploy Storybook to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install NPM dependencies
        run: yarn
      - name: Install Glypfig
        run: yarn add glypfig
      - name: Run Glypfig
        run: npx glypfig -a $API_KEY -k $FILE_KEY -n $NODE_ID -f jpg,png,svg,pdf,react -p -t tsx
        env:
          API_KEY: ${{ secrets.FIGMA_API_KEY }}
          FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          NODE_ID: ${{ secrets.FIGMA_NODE_ID }}
      - name: Build Storybook
        run: yarn build-storybook
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Storybook directory
        uses: actions/upload-pages-artifact@v1
        with:
          path: './storybook-static'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
