# Workflow for publishing NPM package to NPM registry and GitHub Packages when a release is created
name: Publish NPM package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to NPM registry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          cache: yarn
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - run: yarn install --frozen-lockfile
      - name: Publish to Github registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish

