# Workflow for publishing NPM package to NPM registry and GitHub Packages when a release is created
name: Publish NPM package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to NPM registry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Install repo dependencies
        run: yarn install --frozen-lockfile
      - name: Publish to NPM registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
          scope: '@laitine'
      - name: Install repo dependencies
        run: yarn install --frozen-lockfile
      - name: Publish to Github registry
        run: yarn publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
