# Workflow for publishing NPM package to NPM registry
name: Publish NPM package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to NPM registry
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Install repo dependencies
        run: yarn install --frozen-lockfile
      - name: Run E2E tests
        run: yarn test
        env:
          FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          FIGMA_NODE_ID: ${{ secrets.FIGMA_NODE_ID }}
      - name: Publish to NPM registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
